# Generated by Django 4.2 on 2026-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('email', 'Email')], max_length=50)),
                ('account_name', models.CharField(help_text='Display name for this connection', max_length=255)),
                ('credentials', models.JSONField(default=dict, help_text='Platform-specific credentials')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('email', 'Email')], max_length=50, unique=True)),
                ('api_endpoint', models.URLField()),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('requires_oauth', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_integrations',
            },
        ),
    ]
