# Generated by Django 4.2 on 2026-04-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('content', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['creator', '-created_at'], name='content_creator_dc8e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status'], name='content_status_1dd890_idx'),
        ),
    ]
