# Generated by Django 4.2 on 2026-04-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('wordpress', 'WordPress'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('email', 'Email')], max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_connections',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform_name')},
            },
        ),
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post'), ('social', 'Social Media'), ('newsletter', 'Newsletter')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to=settings.AUTH_USER_MODEL)),
                ('platform_to_publish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.platformconnection')),
            ],
            options={
                'db_table': 'content_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='content.contentdraft')),
            ],
            options={
                'db_table': 'content_approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentdraft',
            index=models.Index(fields=['created_by', '-created_at'], name='content_dra_created_4c799a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdraft',
            index=models.Index(fields=['status'], name='content_dra_status_3bf71c_idx'),
        ),
    ]
