# Generated by Django 4.2 on 2026-04-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_platformconnection_contentdraft_approvalworkflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('target_audience', models.JSONField(default=list, help_text='List of target audience tags')),
                ('goals', models.JSONField(default=list, help_text='List of business goals')),
                ('description', models.TextField(help_text='Business description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_information',
                'ordering': ['-created_at'],
            },
        ),
    ]
