# Generated by Django 4.2 on 2026-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_socialmediaplan_socialmediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
