# Generated by Django 4.2 on 2026-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_socialmediaplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinformation',
            name='plan_duration',
            field=models.CharField(default='7', help_text='Plan duration in days', max_length=10),
        ),
        migrations.AddField(
            model_name='businessinformation',
            name='platforms',
            field=models.JSONField(default=list, help_text='List of selected platforms'),
        ),
    ]
