# Generated by Django 4.2 on 2026-04-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('publication_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_schedules', to='content.content')),
                ('platform_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_schedules', to='platforms.platformaccount')),
            ],
            options={
                'db_table': 'publishing_schedules',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PublishingQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='scheduler.publishingschedule')),
            ],
            options={
                'db_table': 'publishing_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publishingschedule',
            index=models.Index(fields=['status', 'scheduled_time'], name='publishing__status_857386_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingschedule',
            index=models.Index(fields=['content'], name='publishing__content_795bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingqueue',
            index=models.Index(fields=['status'], name='publishing__status_e17a81_idx'),
        ),
    ]
